version: "3"
services:
  eureka:
    image: bangjinseong/podo-eureka:${BUILD_NUMBER}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_NUMBER
    ports:
      - "9761:9761"